name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Unzip and Reorganize Project Files
        run: |
          if ls *.zip 1> /dev/null 2>&1; then
            echo "Zip file found. Unzipping..."
            unzip -o *.zip
          fi

          SETTINGS_PATH=$(find . -name "settings.gradle.kts" -not -path '*/.*' | head -n 1)
          if [ -z "$SETTINGS_PATH" ]; then
            echo "Error: settings.gradle.kts file not found anywhere!"
            exit 1
          fi

          SETTINGS_DIR=$(dirname "$SETTINGS_PATH")
          if [ "$SETTINGS_DIR" != "." ]; then
            echo "Moving files to root..."
            find "$SETTINGS_DIR" -mindepth 1 -maxdepth 1 -exec mv -t . {} +
          fi

          if [ ! -f gradlew ]; then
            echo "Generating Gradle Wrapper..."
            gradle wrapper --gradle-version 9.3.1
          fi
          
      - name: Generate missing debug.keystore
        run: |
          # Creates a fake digital signature file so Android lets us build the app
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        env:
          # Tells Java it is running on a server without a screen to prevent AWT errors
          JAVA_TOOL_OPTIONS: "-Djava.awt.headless=true"
        run: ./gradlew assembleDebug --no-daemon
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
